# Generated by Django 4.1.7 on 2023-02-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserOfFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=11)),
                ('mail', models.CharField(max_length=30)),
            ],
        ),
    ]
