# Generated by Django 4.1.7 on 2023-03-04 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_useroffacility_address_useroffacility_handicap_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('occurrence_date', models.DateTimeField(default=datetime.datetime(2023, 3, 4, 9, 25, 40, 575949))),
                ('name', models.CharField(max_length=50)),
                ('case_name', models.CharField(max_length=50)),
                ('content', models.TextField(default='')),
                ('method', models.TextField(default='')),
                ('result', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='useroffacility',
            name='address',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='useroffacility',
            name='handicap_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useroffacility',
            name='handicap_name',
            field=models.TextField(default='', max_length=300),
        ),
    ]
